#!/bin/bash
#PBS -N test-sith
#PBS -A csc025ewk
#PBS -j oe
#PBS -q batch
#PBS -l nodes=10:ppn=32,walltime=00:60:00

cd $PBS_O_WORKDIR

rm -f conf srv.lck

mpirun -n 4 ./dataspaces_server -s 4 -c 192 &
sleep 2

mpirun -n 64 ./test_get 64 4 4 4 8 64 64 64 50 &

mpirun -n 128 ./test_put 128 4 4 8 64 64 32 50 &

wait

