#!/bin/bash
#PBS -N test-sith
#PBS -A csc025ewk
#PBS -j oe
#PBS -q batch
#PBS -l nodes=15:ppn=32,walltime=00:50:00

cd $PBS_O_WORKDIR

rm -f conf srv.lck

mpirun -npernode 2 -n 4 ./dataspaces_server -s 4 -c 384 &
sleep 2

mpirun -n 128 ./test_get 128 4 4 8 64 64 32 40 &

mpirun -n 256 ./test_put 256 8 4 8 32 64 32 40 &


wait

