#!/bin/bash
#PBS -N test-sith
#PBS -A csc025ewk
#PBS -j oe
#PBS -q batch
#PBS -l nodes=6:ppn=10,walltime=00:30:00

cd $PBS_O_WORKDIR

rm -f conf srv.lck

mpirun -n 4 ./dataspaces_server -s 4 -c 48 &
sleep 2

mpirun -n 16 ./test_put 16 4 4 1 32 32 128 10 &

mpirun -n 32 ./test_get 32 4 4 2 32 32 64 10 &

wait

